### PR TITLE
Add the ability to map ports with external port specified

### PR DESCRIPTION
**Pull request by cannium**
Changed the dependency from `github.com/fd/go-nat` to my forked version. I think it's better to fork `go-nat` under `libp2p`

### CODE REVIEW

**Comment by Stebalien** [comment]
Blocked on discussion here: https://github.com/libp2p/go-libp2p/pull/411

**Comment by Stebalien** [comment]
Status: We had to _revert_ stable port mapping, unfortunately, as routers suck: https://github.com/libp2p/go-nat/pull/8.

Basically, some routers (including my nice tp-link one) won't bother checking for conflicts between UPnP mappings and explicit port forwarding.

**Comment by raulk** [comment]
@Stebalien I guess that was a non-trivial debugging trip. Curious to learn how you got to the end of it!

**Comment by Stebalien** [comment]
I can't remember the details, just that my node went from dialable to undialable.

**Pull request closed without merging**
